version = 0.1
[default.deploy.parameters]
stack_name = "SampleFunction-API"
resolve_s3 = true
s3_prefix = "SampleFunction-API"
region = "YOUR REGION"
profile = "Your AWS PROFILE NAME"  # Specify the AWS profile here
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []